version: '3.9'
name: 'docker-compose-4-dev'
services:
    sqlserver2022:
        container_name: sqlserver2022
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=MyStrong(!)Password
        ports:
            - '1433:1433'
        volumes:
            - sqlserver2022data:/var/opt/mssql/data
            - sqlserver2022log:/var/opt/mssql/log
            - sqlserver2022secrets:/var/opt/mssql/secrets
        image: mcr.microsoft.com/mssql/server:2022-latest

    smtp4dev:
        # Reference
        #   https://github.com/rnwood/smtp4dev/wiki/Configuring-Clients
        #   https://github.com/rnwood/smtp4dev/wiki/Configuration
        container_name: smtp4dev
        ports:
            - '3000:80'
            - '2525:25'
        image: rnwood/smtp4dev

volumes:
    sqlserver2022data:
        driver_opts:
            o: bind
            device: /run/desktop/mnt/host/d/DockerVolume/SqlServer2022/data
            type: none
    sqlserver2022log:
        driver_opts:
            o: bind
            device: /run/desktop/mnt/host/d/DockerVolume/SqlServer2022/log
            type: none
    sqlserver2022secrets:
        driver_opts:
            o: bind
            device: /run/desktop/mnt/host/d/DockerVolume/SqlServer2022/secrets
            type: none
